### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by thijstriemstra** [rm-hull/st7735fb#2]
```
root@neon:/home/pi/projects/pi-test/st7735fb# python3.4 examples/maze.py 
  File "examples/maze.py", line 117
    pygame.draw.lines(screen, borderColor, False, map(lambda (a,b): (scale(a),scale(b)), line))
                                                             ^
SyntaxError: invalid syntax
```

**Comment by thijstriemstra** [comment]
Also:

```
python3.4 examples/maze.py 
I'm running under X display = :0.0
Framebuffer size: 1824 x 984
Traceback (most recent call last):
  File "examples/maze.py", line 132, in <module>
    demo(5)
  File "examples/maze.py", line 129, in demo
    Maze(sz).render(fb.screen, borderColor, lambda z: z * scale)
  File "examples/maze.py", line 24, in __init__
    self.generate()
  File "examples/maze.py", line 80, in generate
    self.data = [ NORTH | WEST ] * self.size
TypeError: can't multiply sequence by non-int of type 'float'
```
